name: test

on:
  push:
    tags: "*"
    branches: "*"

jobs:
  version-match:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install yq
        run: sudo snap install yq
      - name: Ensure version equality
        run: |
          echo $GITHUB_REF
          echo $(echo $GITHUB_REF | sed s+refs/tags/++)
          echo $(yq r helm/values.yaml 'deployment.image' | cut -d ':' -f2)
          if [[ "$(echo $GITHUB_REF | sed s+refs/tags/++)" == "" ]] \
          || [[ "$(echo $GITHUB_REF | sed s+refs/tags/++)" != "$(yq r helm/values.yaml 'deployment.image' | cut -d ':' -f2)" ]]
            then exit 1
          fi
